# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RepoFinder' do
	# Comment the next line if you don't want to use dynamic frameworks
	use_frameworks!

	# Pods for RepoFinder
	pod 'Kingfisher', '~> 5.13'
	pod 'SwiftyJSON', '~> 5.0'
	pod 'Alamofire', '5.0.0-rc.3'
	pod 'SWCompression', '~> 4.5'
	

	target 'RepoFinderTests' do
		inherit! :search_paths
		# Pods for testing
	end

	target 'RepoFinderUITests' do
		# Pods for testing
	end
end
